server:
  port: 8060

spring:
  application:
    name: notification

  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5433/notification
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  zipkin:
    baseUrl: http://localhost:9411

  rabbitmq:
    addresses: amqp://localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key