server:
  port: 8060

spring:
  application:
    name: notification

  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  zipkin:
    baseUrl: http://zipkin:9411

  rabbitmq:
    addresses: amqp://rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8765/eureka
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key